# Generated by Django 5.0.4 on 2024-04-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_projects_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='project',
            name='text',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.URLField(default='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='Default description', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
