# Generated by Django 5.0.4 on 2024-05-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_project_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='img_url',
            field=models.CharField(default='default_image_url.jpg', max_length=100),
        ),
    ]
